//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaNotes.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaNotes.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About the movie.
        /// </summary>
        public static string AboutTheMovie_Locale {
            get {
                return ResourceManager.GetString("AboutTheMovie_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Box Office.
        /// </summary>
        public static string BoxOffice_Locale {
            get {
                return ResourceManager.GetString("BoxOffice_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse.
        /// </summary>
        public static string Browse_Locale {
            get {
                return ResourceManager.GetString("Browse_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Country.
        /// </summary>
        public static string Country_Locale {
            get {
                return ResourceManager.GetString("Country_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Director.
        /// </summary>
        public static string Director_Locale {
            get {
                return ResourceManager.GetString("Director_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Genre.
        /// </summary>
        public static string Genre_Locale {
            get {
                return ResourceManager.GetString("Genre_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IMDb Rating.
        /// </summary>
        public static string IMDbRating_Locale {
            get {
                return ResourceManager.GetString("IMDbRating_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main actors.
        /// </summary>
        public static string MainActors_Locale {
            get {
                return ResourceManager.GetString("MainActors_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metascore.
        /// </summary>
        public static string Metascore_Locale {
            get {
                return ResourceManager.GetString("Metascore_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на min..
        /// </summary>
        public static string MinuteShort_Locale {
            get {
                return ResourceManager.GetString("MinuteShort_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plot.
        /// </summary>
        public static string Plot_Locale {
            get {
                return ResourceManager.GetString("Plot_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rated.
        /// </summary>
        public static string Rated_Locale {
            get {
                return ResourceManager.GetString("Rated_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Released.
        /// </summary>
        public static string Released_Locale {
            get {
                return ResourceManager.GetString("Released_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Runtime.
        /// </summary>
        public static string Runtime_Locale {
            get {
                return ResourceManager.GetString("Runtime_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Watchlist.
        /// </summary>
        public static string Watchlist_Locale {
            get {
                return ResourceManager.GetString("Watchlist_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no movies in the watchlist yet You may to go to the second tab for browsing and adding a movie you would like to watch..
        /// </summary>
        public static string WelcomeMessageText_Locale {
            get {
                return ResourceManager.GetString("WelcomeMessageText_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to MediaNotes!.
        /// </summary>
        public static string WelcomeMessageTitle_Locale {
            get {
                return ResourceManager.GetString("WelcomeMessageTitle_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writers.
        /// </summary>
        public static string Writers_Locale {
            get {
                return ResourceManager.GetString("Writers_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year.
        /// </summary>
        public static string Year_Locale {
            get {
                return ResourceManager.GetString("Year_Locale", resourceCulture);
            }
        }
    }
}
